services:
  traefik:
    image: traefik:v3.0
    environment:
      - DOCKER_API_VERSION=1.54
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # optional dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=admin
      - GEOSERVER_PROXY_BASE_URL=https://amp-gis.dgstg.org/geoserver
      - GEOSERVER_CSRF_DISABLED=true
      - GEOSERVER_CSRF_WHITELIST=amp-gis.dgstg.org
      - PROXY_BASE_URL=https://amp-gis.dgstg.org/geoserver
      - GEOSERVER_DATA_DIR=/opt/geoserver_data
    volumes:
      - ./geoserver_data:/opt/geoserver_data
    networks:
      - web
    labels:
      - "traefik.enable=true"

      # Route GeoServer under /geoserver
      - "traefik.http.routers.geoserver.rule=PathPrefix(`/geoserver`)"
      - "traefik.http.routers.geoserver.entrypoints=web"

      # Strip prefix before forwarding
      #- "traefik.http.middlewares.geoserver-strip.stripprefix.prefixes=/geoserver"
      #- "traefik.http.routers.geoserver.middlewares=geoserver-strip"

      # Internal port
      - "traefik.http.services.geoserver.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.geoserver.middlewares=forward-headers"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: geoserver-frontend
    networks:
      - web
    depends_on:
      - geoserver
    labels:
      - "traefik.enable=true"
      # Route GeoServer under /geoserver
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"

       # Internal port
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.middlewares.forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.frontend.middlewares=forward-headers"

networks:
  web:
